apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: consulserviceacl.composite.daanvinken
spec:
  compositeTypeRef:
    apiVersion: daanvinken.io/v1
    kind: ConsulServiceACL
  resources:
    # Consul ACL Policy Resource
    - name: consul_acl_policy
      base:
        apiVersion: acl.daanvinken.io/v1alpha1
        kind: Policy
        metadata:
          labels:
            crossplane.io/composite: "consulserviceacl" # Simplified label
        spec:
          forProvider:
            datacenters:
              - dc1
            rules: "" # Patch later

      patches:
        - fromFieldPath: "metadata.name"  # Use composite name as part of policy name
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "policy-%s"
        # Inject composite name into the `rules` field dynamically
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.rules"
          transforms:
            - type: string
              string:
                fmt: |
                  agent_prefix "" {
                      policy = "read"
                  }

                    service_prefix "" {
                    policy = "read"
                  }

                    service_prefix "%[1]s" {
                    policy = "write"
                  }

                    key_prefix "%[1]s" {
                    policy = "write"
                  }

                    key_prefix "app/%[1]s" {
                    policy = "write"
                  }

                    session_prefix "" {
                    policy = "write"
                  }

                    session_prefix "session/%[1]s" {
                    policy = "write"
                  }

                    key_prefix "preloader/%[1]s" {
                    policy = "write"
                  }

    # Consul ACL Role Resource
    - name: consul_acl_role
      base:
        apiVersion: acl.daanvinken.io/v1alpha1
        kind: Role
        spec:
          forProvider:
            name: "placeholder"
            description: "ACL Role for service"
            serviceIdentities:
              - serviceName: "foo"
      patches:
        - fromFieldPath: "spec.parameters.service"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "role-%s"
        # Reference the Policy dynamically based on the unique composite name
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.policies[0]"
          transforms:
            - type: string
              string:
                fmt: "policy-%s"
    # Consul ACL Token Resource
    - name: consul_acl_token
      base:
        apiVersion: acl.daanvinken.io/v1alpha1
        kind: Token
        spec:
          forProvider:
            description: "Generated by Crossplane"
      patches:
        - fromFieldPath: "spec.parameters.service"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "role-%s"
        # Reference the Policy dynamically based on the unique composite name
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.policies[0]"
          transforms:
            - type: string
              string:
                fmt: "policy-%s"
