apiVersion: consul.daanvinken.io/v1beta1
kind: ProviderConfig
metadata:
  name: myfirstconfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
