apiVersion: acl.daanvinken.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    datacenters:
    - dc1
    name: my_policy
    rules: |
      node_prefix "" {
        policy = "read"
      }
