apiVersion: acl.daanvinken.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/token
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: my test token
    local: true
    policies:
    - ${consul_acl_policy.agent.name}

---

apiVersion: acl.daanvinken.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/token
  labels:
    testing.upbound.io/example-name: agent
  name: agent
spec:
  forProvider:
    name: agent
    rules: |
      node_prefix "" {
        policy = "read"
      }
