apiVersion: acl.daanvinken.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/token
  name: node-token
spec:
  forProvider:
    description: my test token
    local: true
    policies:
      - agent
---
apiVersion: acl.daanvinken.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/token
  labels:
    testing.upbound.io/example-name: agent
  name: agent
spec:
  forProvider:
    name: agent
    rules: |
      node_prefix "" {
        policy = "read"
      }
---
apiVersion: acl.daanvinken.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/role
  labels:
    testing.upbound.io/example-name: read
  name: read
spec:
  forProvider:
    description: bar
    name: foo
    policies:
      - agent
    serviceIdentities:
      - serviceName: foo