apiVersion: daanvinken.io/v1alpha1
kind: AdyenCompute
metadata:
  name: adyencompute-example-daan
spec:
  parameters:
    computeInstanceName: "crossplane-instance-daan"
    imageName: "cirros"
    flavorName: "1C-500M-1G-STG1-CIRROS"
    network:
      - name: osstg1test
    securityGroups:
      - default
    consulServices:
      - serviceName: acr-staging
        main_keys: true
      - serviceName: artifacts-something
        main_keys: false
    consultAgent: true
    providerConfigName: "openstack-ams2-nonprod"
