apiVersion: cert.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: "cert-auth-role"
spec:
  forProvider:
    name: "puppet-test-cert-role"  # Name of the role in Vault
    backend: "puppet"  # Specifies the cert auth backend path
    certificate: | 

    allowedCommonNames:
      - "puppet-client"
    tokenTtl: 86400
    tokenMaxTtl: 86400
    tokenPolicies:
      - "puppet-policy"